### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by ranggatea** [Caliph91/api-lolis#1]
gak ada masalah cuma cara pake nya gimana udah ku install di heruko cuma gak tau lagi cara nya :v 
wkwkwkwkwk

**Comment by ranggatea** [comment]
masih pemula

**Comment by ranggatea** [comment]
ajarin kalau bisa :v

**Comment by Caliph91** [comment]
> ajarin kalau bisa :v

Pake heroku, vercel, replit, dll
